services:
  postgres:
    image: postgres:17
    container_name: postgres
    environment:
      TZ: Asia/Seoul
      POSTGRES_USER: nomadsquare
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: nomadsquare_db
    ports:
      - "5432:5432"
    volumes:
      # - D:/NomadSquare/dockerData/dev/postgres:/var/lib/postgresql/data   # 개발 데이터
      - D:/NomadSquare/postgres/entrypoint:/docker-entrypoint-initdb.d:ro
      # - D:/NomadSquare/postgres/entrypoint/00_init.sql:/docker-entrypoint-initdb.d/00_init.sql
    restart: unless-stopped
    networks:
      - mynet

  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    environment:
      TZ: Asia/Seoul
    depends_on:
      - sveltekit
      - django
      # - fastapi
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf  # conf 파일만 직접 마운트
      - D:/NomadSquare/dockerData/dev/logs/nginx:/var/log/nginx    # 개발 로그
    restart: unless-stopped
    networks:
      - mynet


# 도커 네트워크 생성
# docker network create mynet
networks:
  mynet:
    driver: bridge

